=== hmrc/secure-message/conf/message.schema.v4.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "externalRef": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "A unique ID for this message generated by the calling service"
        },
        "source": {
          "type": "string",
          "description": "The source of this message i.e. mdtp"
        }
      },
      "required": [
        "id",
        "source"
      ]
    },
    "recipient": {
      "type": "object",
      "properties": {
        "regime": {
          "type": "string",
          "description": "Regime"
        },
        "taxIdentifier": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "The tax identifier name to which this message relates."
            },
            "value": {
              "type": "string",
              "description": "The recipient customer's tax identifier value."
            }
          },
          "required": [
            "name",
            "value"
          ]
        },
        "name": {
          "type": "object",
          "properties": {
            "line1": {
              "type": "string",
              "description": "The name of the recipient, for example “John Paul Smith” or “Mr. J Smith”."
            },
            "line2": {
              "type": "string",
              "description": "A second name line for the recipient."
            },
            "line3": {
              "type": "string",
              "description": "A third name line for the recipient."
            }
          }
        },
        "email": {
          "type": "string",
          "description": "If provided, the notification email for this message will be sent to this email address."
        }
      },
      "required": [
        "regime",
        "taxIdentifier"
      ]
    },
    "tags": {
      "type": "object",
      "properties": {
        "notificationType": {
          "type": "string",
          "description": "Notification type"
        }
      }
    },
    "messageType": {
      "type": "string",
      "description": "This is used to determine the email alert to use for this message."
    },
    "language": {
      "type": "string",
      "description": "This is optional, will be used to determine the language sets for email subjaect"
    },
    "validFrom": {
      "type": "string",
      "format": "date",
      "description": "The date on which this message becomes valid."
    },
    "content": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "lang": {
              "type": "string",
              "minLength": 1,
              "pattern": "^\\S.*$",
              "description": "Content language i.e. 'en' or 'cy'"
            },
            "subject": {
              "type": "string",
              "minLength": 1,
              "pattern": "^\\S.*$",
              "description": "Subject line"
            },
            "body": {
              "type": "string",
              "minLength": 1,
              "pattern": "^\\S.*$",
              "description": "<base64 encoded source data>"
            }
          },
          "required": [
            "lang",
            "subject",
            "body"
          ]
        }
      ]
    },
    "alertDetails": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object",
          "properties": {
            "key1": {
              "type": "string",
              "description": "Key 1"
            },
            "key2": {
              "type": "string",
              "description": "Key 2"
            }
          },
          "required": [
            "key1",
            "key2"
          ]
        }
      },
      "required": [
        "data"
      ]
    },
    "alertQueue": {
      "type": "string",
      "description": "The email messaging queue to place the email alert for this message onto."
    },
    "details": {
      "type": "object",
      "properties": {
        "formId": {
          "type": "string",
          "description": "The form ID of the message that we are sending."
        },
        "issueDate": {
          "type": "string",
          "format": "date",
          "description": "The date this message was created by the source system."
        },
        "batchId": {
          "type": "string",
          "description": "If this message is part of a 'batch' or 'print' run that has an ID, then specify this here."
        },
        "sourceData": {
          "type": "string",
          "description": "This is the source data that GMC received in the HODS file for this message."
        },
        "properties": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "property": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "minLength": 1,
                      "pattern": "^\\S.*$"
                    },
                    "value": {
                      "type": "string",
                      "minLength": 1,
                      "pattern": "^\\S.*$"
                    }
                  },
                  "required": [
                    "name",
                    "value"
                  ]
                }
              },
              "required": [
                "property"
              ]
            }
          ]
        }
      },
      "required": [
        "formId"
      ]
    }
  },
  "required": [
    "externalRef",
    "recipient",
    "messageType",
    "content"
  ]
}

=== hmrc/secure-message/app/uk/gov/hmrc/securemessage/controllers/test.json
{
  "externalRef": {
    "id": "ANJ241434432110001",
    "source": "mdtp"
  },
  "recipient": {
    "regime": "sdil",
    "taxIdentifier": {
      "name": "HMRC-OBTDS-ORG",
      "value": "XVSDIL000100389"
    },
    "name": {
      "line1": "Anjali",
      "line2": "Padmanabhan",
      "line3": "Nair"
    },
    "email":"anjali.nair@digital.hmrc.gov.uk"
  },
  "content": [
    {
      "lang": "en",
      "subject": "Send your quarterly Income Tax update",
      "body": "PGRpdiBjbGFzcz0iZ292dWstZ3JpZC1yb3cgZ3JpZC1yb3ciPg0KPGRpdiBjbGFzcz0iZ292dWstZ3JpZC1jb2x1bW4tdHdvLXRoaXJkcyBjb2x1bW4tdHdvLXRoaXJkcyI+DQo8c2VjdGlvbiBsYW5nPSJlbiI+DQo8cCBjbGFzcz0iZ292dWstYm9keSI+WW91IG11c3Qgc2VuZCB1cyB5b3VyIGluY29tZSBhbmQgZXhwZW5zZXMgdXBkYXRlIGZvciB5b3VyIGZvcmVpZ24gcHJvcGVydHkgaW5jb21lIGZvciB0aGUgcXVhcnRlciBlbmRpbmcgMDUgSnVseSAyMDIwLjwvcD4NCjxwIGNsYXNzPSJnb3Z1ay1ib2R5Ij5Zb3UgbmVlZCB0byBzZW5kIHRoZSB1cGRhdGVzIHRvIHVzIG9uIG9yIGJlZm9yZSAwNSBBdWd1c3QgMjAyMC48L3A+DQo8cCBjbGFzcz0iZ292dWstYm9keSI+V2UgbWF5IGF3YXJkIHlvdSBhIHBlbmFsdHkgaWYgeW91ciBxdWFydGVybHkgdXBkYXRlcyBhcmUgbGF0ZS48L3A+DQo8cCBjbGFzcz0iZ292dWstYm9keSI+SXQgaXMgeW91ciByZXNwb25zaWJpbGl0eSB0byBtYWtlIHN1cmUgeW91IHNlbmQgdXMgYWxsIG5lY2Vzc2FyeSBzdWJtaXNzaW9ucy4gSWYgeW91IGhhdmUgYW4gYWdlbnQsIHlvdSBtYXkgd2FudCB0byBkaXNjdXNzIHRoaXMgcmVtaW5kZXIgd2l0aCB0aGVtLjwvcD4NCjxwIGNsYXNzPSJtZXNzYWdlX3RpbWUgZmFkZWQtdGV4dC0tc21hbGwgZ292dWstYm9keS1zIj5NZXNzYWdlIHJlZmVyZW5jZSYjNTg7IElUU0FRVTEgMDUvMjIgMS4wPC9wPg0KPC9zZWN0aW9uPg0KPC9kaXY+DQo8L2Rpdj4="
    },
    {
      "lang": "cy",
      "subject": "Anfonwch eich diweddariad Treth Incwm chwarterol",
      "body": "PGRpdiBjbGFzcz0iZ292dWstZ3JpZC1yb3cgZ3JpZC1yb3ciPgo8ZGl2IGNsYXNzPSJnb3Z1ay1ncmlkLWNvbHVtbi10d28tdGhpcmRzIGNvbHVtbi10d28tdGhpcmRzIj4KPHNlY3Rpb24gbGFuZz0iY3kiPgo8cCBjbGFzcz0iZ292dWstYm9keSI+UmhhaWQgaSBjaGkgYW5mb24gZWljaCBkaXdlZGRhcmlhZCBpbmN3bSBhIHRocmV1bGlhdSBhciBneWZlciBlaWNoIGluY3dtIG8gZWlkZG8gdHJhbW9yIGFyIGd5ZmVyIHkgY2h3YXJ0ZXIgeW4gZGl3ZWRkdSAwNSBHb3JmZmVubmFmIDIwMjAgYXRvbS48L3A+CjxwIGNsYXNzPSJnb3Z1ay1ib2R5Ij5NYWUgYW5nZW4gaSBjaGkgYW5mb24geSBkaXdlZGRhcmlhZGF1IGF0b20gYXIgbmV1IGN5biAwNSBBd3N0IDIwMjAuPC9wPgo8cCBjbGFzcz0iZ292dWstYm9keSI+TWFl4oCZbiBib3NpYmwgeSBieWRkd24geW4gcmhvaSBjb3NiIGkgY2hpIG9zIGJ5ZGQgZWljaCBkaXdlZGRhcmlhZGF1IGNod2FydGVyb2wgeW4gaHd5ci48L3A+CjxwIGNsYXNzPSJnb3Z1ay1ib2R5Ij5FaWNoIGN5ZnJpZm9sZGViIGNoaSB5dyBzaWNyaGF1IGVpY2ggYm9kIHluIGFuZm9uIHlyIGhvbGwgZ3lmbHd5bmlhZGF1IGFuZ2VucmhlaWRpb2wgYXRvbS4gT3Mgb2VzIGdlbm55Y2ggYXNpYW50LCBlZmFsbGFpIHkgYnlkZHdjaCBhbSBkcmFmb2QgeSBub2R5biBhdGdvZmZhIGh3biBneWRhIG5ody48L3A+CjxwIGNsYXNzPSJtZXNzYWdlX3RpbWUgZmFkZWQtdGV4dC0tc21hbGwgZ292dWstYm9keS1zIj5DeWZlaXJub2QgeSBuZWdlcyYjNTg7IElUU0FRVTEgMDUvMjIgMS4wPC9wPgo8L3NlY3Rpb24+CjwvZGl2Pgo8L2Rpdj4="
    }
  ],
  "messageType": "newMessageAlert",
  "validFrom": "2023-03-13",
  "alertQueue": "DEFAULT"
}
